import Layout from "@/components/Layout";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Login from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import { Toaster } from "react-hot-toast";
import Provider from "@/components/Provider";
import EditModal from "@/components/modals/EditModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Bitter",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Provider>
				<body className={inter.className}>
					<Toaster />
					<EditModal />
					<RegisterModal />
					<Login />
					<Layout>{children}</Layout>
				</body>
			</Provider>
		</html>
	);
}
